name: stream
version: 0.5.0+2
description: > 
  Stream is a Dart web server supporting URI mapping, templating, file-based static resources
  and MVC design pattern.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org
dependencies:
  rikulo_commons: any
  logging: any
  args: any
