name: stream
version: 0.8.0+1
description: > 
  A Dart web server supporting request routing, filtering,
  template engine, file-based static resources and MVC design pattern.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream
dependencies:
  rikulo_commons: any
  logging: any
  args: any
  meta: any
  path: any
